name: GCC Workflow #give this pipeline an actual name
on: push
jobs:
  Building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependancies
        run: |
          sudo apt-get install clang
          sudo apt-get install valgrind
      - name: Build targets using compilers C++11 -> C++20
        run: |
          cd ./.testing/
          make -f Makefile COMP=clang++ STD=--std=c++11
          make -f Makefile COMP=clang++ STD=--std=c++14
          make -f Makefile COMP=clang++ STD=--std=c++17
          make -f Makefile COMP=clang++ STD=--std=c++2a
  Testing:
    needs: [Building]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Store all testing filenames and store in a file
        run: |
          cd ./.testing/
          find . -maxdepth 1 -perm -111 -type f >> gfilestest.log
      - name: Loop through & Run files
        run: |
          cd ./.testing/
          input="./gfilestest.log"
          while read line
          do
            ./"$line"
          done < "$input"
      - name: Delete temporary file name holder
        run: rm ./.testing/gfilestest.log
  Memory-Leaks:
    needs: [Building]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Store all testing filenames and store in a file
        run: |
          cd ./.testing/
          find ./exes -maxdepth 1 -perm -111 -type f >> gfilesmem.log
      - name: Create valgrind alias with specific testing and return type
        run: alias vg='valgrind --error-exitcode=1 --leak-check=full -v --track-origins=yes'
      - name: Loop through & run valgrind for each one
        run: |
          cd ./.testing/
          input="./gfilesmem.log"
          while read line
          do
            vg ./"$line"
          done < "$input"
      - name: Delete temporary file name holder
        run: rm ./.testing/gfilesmem.log
