name: Make

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependancies
      run: |
        sudo apt install g++
        sudo wget --no-check-certificate https://github.com/catchorg/Catch2/releases/download/v2.13.4/catch.hpp 
    - name: Place files in correct directories
      run: |
        sudo cp -r . /usr/include/c++/9/
        sudo mkdir /usr/include/c++/9/testing/
        sudo mv catch.hpp /usr/include/c++/9/testing/
    - name: Make tests
      run: |
        cd ./.testing/
        make
