name: Make

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependancies
      run: |
        sudo apt install g++
    - name: Place files in correct directories
      run: |
        sudo ln -sf . /usr/include/c++/9/lib
    - name: Make tests
      run: |
        cd ./.testing/
        make
