name: Testing #give this pipeline an actual name
on:
  push:
    branches-ignore:
      - master
      - main
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Navigate to testing folder
      - run: cd ./.testing/exes/
      - name: Store all testing filenames and store in a file
      - run: find . -maxdepth 1 -perm -111 -type f >> files.log
      - name: Loop through & Run files
      - run: |
          input=".files.log"
          while IFS= read -r line
          do
            ./"$line"
          done < "$input"
