name: Testing #give this pipeline an actual name
on:
  push:
    branches-ignore:
      - master
      - main
jobs:
  Make-waiting:
    runs-on: ubuntu-latest
    steps:
     - name: Wait for build to succeed
       uses: fountainhead/action-wait-for-check@v1.0.0
       id: wait-for-build
       with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: build
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
     - name: Do something with a passing build
       if: steps.wait-for-build.outputs.conclusion == 'success'
     - name: Do something with a failing build
       if: steps.wait-for-build.outputs.conclusion == 'failure'
  Testing:
    needs: [Make-waiting]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Navigate to testing folder
        run: cd ./.testing/exes/
      - name: Store all testing filenames and store in a file
        run: find . -maxdepth 1 -perm -111 -type f >> files.log
      - name: Loop through & Run files
        run: |
          input="./files.log"
          while IFS= read -r line
          do
            ./"$line"
          done < "$input"
      - name: Delete temporary file name holder
        run: rm files.log
